build:
	g++ -o main main.cpp -std=c++2a -O3 -Wall -Wextra -Wshadow -Wnon-virtual-dtor -pedantic
build_debug:
	g++ -g -o main main.cpp -std=c++2a -O3 -Wall -Wextra -Wshadow -Wnon-virtual-dtor -pedantic
run:
	./main