build:
	g++ -o main main.cpp -std=c++17 -O3 -Wall -Wextra -Wshadow -Wnon-virtual-dtor -pedantic
build_debug:
	g++ -g -o main main.cpp -std=c++17 -O0 -Wall -Wextra -Wshadow -Wnon-virtual-dtor -pedantic
run:
	./main